apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-service
  namespace: review
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - name: review-service
          image: roin09/review-service:latest
          ports:
            - containerPort: 8087
          envFrom:
            - configMapRef:
                name: review-service-config
            - secretRef:
                name: review-service-secret
