apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: review-service-secret
  namespace: review
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: review-service-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: review-service-secret
